/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface InitVolumeOptions {
  name: string
  dev?: boolean
  metadata?: string
  store?: string
  storage?: string
  bucket?: string
}
export interface MountVolumeOptions {
  name: string
  path: string
  checkStorage?: boolean
}
export interface UnmountOptions {
  force?: boolean
}
export interface VolumeInfo {
  name: string
  metadataUrl: string
  storage: string
  bucket: string
  dev: boolean
  mountpoint?: string
}
export interface MountInfo {
  name: string
  mountpoint: string
}
export interface Status {
  volumes: Array<VolumeInfo>
}
export interface BinaryReport {
  found: boolean
  path?: string
  version?: string
  managed: boolean
}
export interface MountSupportReport {
  found: boolean
  detail: string
  fix?: string
}
export interface DoctorReport {
  home: string
  config: string
  storageBackend: BinaryReport
  mountSupport: MountSupportReport
}
export declare function doctor(): DoctorReport
export type SmolFs = SmolFS
export declare class SmolFS {
  constructor()
  static fromEnv(): SmolFs
  doctor(): DoctorReport
  init(options: InitVolumeOptions): VolumeInfo
  ensureVolume(options: InitVolumeOptions): VolumeInfo
  mount(options: MountVolumeOptions): MountInfo
  flush(name: string): void
  unmount(name: string, options?: UnmountOptions | undefined | null): void
  status(name?: string | undefined | null): Status
}
